# basic options
title: Garage Sale
author: Anthony & Heidrun
# email: your-email@domain.com
description: Selling stuff that's been lying around forever...
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
